from fastapi import APIRouter
from app.api.v1.endpoints import auth, debug, ai_tutor, recommendations, goals, notes, analytics, bookmarks, exams, branches, subjects, chapters, topics, questions, practice, mock_tests, flashcards, admin

api_router = APIRouter()
api_router.include_router(auth.router, prefix="/auth", tags=["Authentication"])
api_router.include_router(debug.router, prefix="/debug")
api_router.include_router(admin.router, prefix="/admin", tags=["Admin"])
api_router.include_router(exams.router, prefix="/exams", tags=["Exams"])
api_router.include_router(branches.router, prefix="/branches", tags=["Branches"])
api_router.include_router(subjects.router, prefix="/subjects", tags=["Subjects"])
api_router.include_router(chapters.router, prefix="/chapters", tags=["Chapters"])
api_router.include_router(topics.router, prefix="/topics", tags=["Topics"])
api_router.include_router(questions.router, prefix="/questions", tags=["Questions"])
api_router.include_router(practice.router, prefix="/practice", tags=["Practice"])
api_router.include_router(mock_tests.router, prefix="/mock-tests", tags=["Mock Tests"])
api_router.include_router(bookmarks.router, prefix="/bookmarks", tags=["Bookmarks"])
api_router.include_router(analytics.router, prefix="/analytics", tags=["Analytics"])
api_router.include_router(goals.router, prefix="/goals", tags=["Goals"])
api_router.include_router(notes.router, prefix="/notes", tags=["Notes"])
api_router.include_router(flashcards.router, prefix="/flashcards", tags=["Flashcards"])
api_router.include_router(recommendations.router, prefix="/recommendations", tags=["Recommendations"])
api_router.include_router(ai_tutor.router, prefix="/ai-tutor", tags=["AI Tutor"])
